#index:
#   path: /
#  controller: App\Controller\AccueilController::bonjour

# index:
#    path: /commandes
#    controller: App\Controller\CommandeController::recap

# newIntervenant_success:
#     path: /newintersuccess
#     controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
#     defaults:
#         template: "intervenant/static/success.html.twig"   